export enum UploadStatus {
  PENDING = "PENDING",
  UPLOADING = "UPLOADING",
  PROCESSING = "PROCESSING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum FileViewMode {
  GRID = "GRID",
  LIST = "LIST",
}

export enum SortBy {
  NAME_ASC = "NAME_ASC",
  NAME_DESC = "NAME_DESC",
  DATE_ASC = "DATE_ASC",
  DATE_DESC = "DATE_DESC",
  SIZE_ASC = "SIZE_ASC",
  SIZE_DESC = "SIZE_DESC",
}

export enum CacheStrategy {
  CACHE_FIRST = "CACHE_FIRST",
  NETWORK_FIRST = "NETWORK_FIRST",
  STALE_WHILE_REVALIDATE = "STALE_WHILE_REVALIDATE",
  NETWORK_ONLY = "NETWORK_ONLY",
  CACHE_ONLY = "CACHE_ONLY",
}
