export const NERDY_QUOTES = [
  "May the Force be with you.",
  "I am your father.",
  "Do. Or do not. There is no try.",
  "It's a trap!",
  "I've got a bad feeling about this.",
  "Never tell me the odds.",
  "These aren't the droids you're looking for.",
  "Help me, Obi-Wan Kenobi. You're my only hope.",
  "I find your lack of faith disturbing.",
  "One does not simply walk into Mordor.",
  "You shall not pass!",
  "My precious.",
  "Even the smallest person can change the course of the future.",
  "All we have to decide is what to do with the time that is given us.",
  "I'll be back.",
  "Hasta la vista, baby.",
  "Come with me if you want to live.",
  "There is no spoon.",
  "Free your mind.",
  "Welcome to the real world.",
  "I know kung fu.",
  "Roads? Where we're going, we don't need roads.",
  "Great Scott!",
  "1.21 gigawatts!",
  "Life, uh, finds a way.",
  "Clever girl.",
  "Hold on to your butts.",
  "Open the pod bay doors, HAL.",
  "I'm sorry, Dave. I'm afraid I can't do that.",
  "All those moments will be lost in time, like tears in rain.",
  "I'm going to need a bigger boat.",
  "Who you gonna call?",
  "Don't cross the streams.",
  "We came, we saw, we kicked its ass.",
  "Live long and prosper.",
  "Resistance is futile.",
  "Make it so.",
  "Beam me up, Scotty.",
  "Khaaan!",
  "To infinity and beyond!",
  "I am Groot.",
  "I am Iron Man.",
  "Avengers, assemble.",
  "With great power comes great responsibility.",
  "Why so serious?",
  "I'm Batman.",
  "Wakanda forever!",
  "We're in the endgame now.",
  "Wax on, wax off.",
  "Nobody puts Baby in a corner.",
  "Inconceivable!",
  "Hello. My name is Inigo Montoya. You killed my father. Prepare to die.",
  "As you wish.",
  "There can be only one!",
  "Game over, man! Game over!",
  "Mischief managed.",
  "In space, no one can hear you scream.",
  "E.T. phone home.",
  "It's alive! It's alive!",
  "Say hello to my little friend.",
  "Here's Johnny!",
  "Snakes. Why'd it have to be snakes?",
  "It belongs in a museum!",
  "After all this time? Always.",
  "Fasten your seatbelts, it's going to be a bumpy night.",
  "Shall we play a game?",
  "Greetings, programs!",
  "End of line.",
  "Hack the planet!",
  "The cake is a lie.",
] as const;
